//go:build linux

package bwrap

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// pastaBin is the passt project's namespace-mode binary.
const pastaBin = "pasta"

// dnsForwardAddr is the address pasta answers DNS on inside the box's network
// namespace, and the sole nameserver the box's resolv.conf names. It is in the
// link-local range so it cannot collide with a real resolver the recipe mounts
// a config for. pasta forwards those queries to the host's own upstream
// resolvers, so the box resolves names without any route to a host address.
const dnsForwardAddr = "169.254.1.1"

// geteuid is os.Geteuid, named so a test can pose as an unprivileged caller.
var geteuid = os.Geteuid

// requirePasta reports the path of the pasta that will build an open-egress
// box's namespace, or the message a host that cannot have one gets. It reads
// the two conditions pasta itself cannot be asked about later — a caller that
// is root, and a pasta that is not installed — so a boot that cannot get the
// namespace stops here. It does not report on the flags this pasta understands:
// those the invocation carries, and a pasta too old for one refuses aloud on
// the first enter.
func requirePasta() (string, error) {
	if geteuid() == 0 {
		return "", fmt.Errorf("bwrap: egress: open needs pasta to build the box's network namespace, and pasta cannot serve a root caller: it drops its capabilities before mapping the namespace's users, so the namespace comes up with no mapping and bwrap cannot enter it. Run dabs as an unprivileged user (the bwrap driver needs no privilege), or give the recipe egress: none or a proxy egress")
	}
	path, err := exec.LookPath(pastaBin)
	if err != nil {
		return "", fmt.Errorf("bwrap: 'pasta' not found; egress: open gives a box its own network namespace and needs pasta (the passt project) to carry its traffic out; install the 'passt' package: " +
			"apt install passt (Debian/Ubuntu) · dnf install passt (Fedora/RHEL) · apk add passt (Alpine) · pacman -S passt (Arch) · zypper install passt (openSUSE)")
	}
	return path, nil
}

// pastaArgs is the pasta invocation that runs inner in a fresh network
// namespace of its own. Each flag buys one property of that namespace:
//
//	--config-net       address, route and MTU set up inside the namespace
//	--dns-forward      a resolver the box can reach, proxied to the host's
//	--tcp-ports none   nothing the box binds is published on the host, so five
//	--udp-ports none   boxes may bind :3000 at the same time
//	--tcp-ns none      and nothing the HOST binds is published in the box, so a
//	--udp-ns none      host service on loopback stays out of the box's reach
//	--no-map-gw        the gateway address does not stand in for the host either
//	--map-guest-addr   and neither does any address standing in for the box
//	--quiet            pasta's own chatter stays out of the command's output
//
// Every address and port translation is named, none left to a default: pasta's
// default for each port direction is `auto`, which mirrors bound ports across
// the namespace boundary and hands back exactly the port space and the host
// reachability the namespace is there to take away. A pasta too old for a flag
// refuses the whole invocation, which is the answer wanted — the alternative is
// a box quietly built to a weaker shape than the one named here.
//
// The exit status the caller sees is the inner command's, except when the inner
// command dies of a SIGNAL: pasta reports that as its own clean exit. A box
// command's own exit codes survive; a bwrap killed by OOM or SEGV reads as
// success.
func pastaArgs(inner []string) []string {
	args := []string{
		"--config-net",
		"--dns-forward", dnsForwardAddr,
		"--tcp-ports", "none",
		"--udp-ports", "none",
		"--tcp-ns", "none",
		"--udp-ns", "none",
		"--no-map-gw",
		"--map-guest-addr", "none",
		"--quiet",
		"--",
	}
	return append(args, inner...)
}

// resolvConfPath is where an instance keeps the resolv.conf its box sees.
func (d Driver) resolvConfPath(instance string) string {
	return filepath.Join(d.instanceDir(instance), "resolv.conf")
}

// writeResolvConf records the resolver the box's namespace can reach. The
// host's own /etc/resolv.conf is not usable inside: it commonly names a
// loopback stub (systemd-resolved, a container runtime's embedded DNS), and
// loopback in the box's namespace is the box's own.
func (d Driver) writeResolvConf(instance string) error {
	body := "# generated by dabs: pasta answers DNS for this box\nnameserver " + dnsForwardAddr + "\n"
	if err := os.WriteFile(d.resolvConfPath(instance), []byte(body), 0o644); err != nil {
		return fmt.Errorf("bwrap: %w", err)
	}
	return nil
}
